server:
  port: 8299

spring:
  application:
    name: diamoncode-messaging

  cloud:
    function:
      definition: email|sms

    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
