global:
  scrape_interval: 5s # Sets the scrape interval to every 5 seconds
  evaluation_interval: 5s # Evaluate the rules every 5 seconds
scrape_configs:
  - job_name: 'accounts'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ accounts:9082 ]
  - job_name: 'loans'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ loans:8090 ]
  - job_name: 'cards'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ cards:9000 ]
  - job_name: 'api_gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ api_gateway:8099 ]